baseURL = "/"  # Ubah ini jadi "/" agar support dynamic preview Vercel
languageCode = "en-us"
title = "US Daily Context"
theme = "neo-news"

[author]
  name = "US News Desk"
  email = "bot@usnews.ai"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "AI-Powered Journalism covering US Top Stories."
  defaultImage = "/images/default-news.jpg"
